stages:
  - build
  - test
  - deploy

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA

build:
  stage: build
  image: docker:19.03
  services:
    - docker:19.03-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG

test:
  stage: test
  image: $IMAGE_TAG
  script:
    - echo "Run tests here"
    - python -m unittest discover

deploy:
  stage: deploy
  image: docker:19.03
  script:
    - docker pull $IMAGE_TAG
    - echo "Deploy commands go here"
    - echo "This could be a script to update a server or a service"
