version: '3.8'
services:
  webapp:
    build: .
    container_name: myci-cli-web
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo
    container_name: myci-cli-mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
