name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Build and Publish Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/myci-cli:${{ github.sha }} .
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker push ${{ secrets.DOCKER_USERNAME }}/myci-cli:${{ github.sha }}

    - name: Push to PyPI
      run: |
        docker run --rm ${{ secrets.DOCKER_USERNAME }}/myci-cli:${{ github.sha }} python setup.py sdist bdist_wheel
        twine upload dist/* --username ${{ secrets.PYPI_USERNAME }} --password ${{ secrets.PYPI_PASSWORD }}
